### ISSUE TITLE
9rush is missing from the gold coast guide - it is in the brisbane one

### ISSUE THREAD

**Issue by vw-kombi** [markcs/xml_tv#67]
Please can you add 9Rush to the gold coast guide data.  Thanks.

**Comment by markcs** [comment]
It makes things easier if you follow the template when you created the issue.  Please can you do that?

***When reporting an issue, please follow this template.  It makes any changes or fixes easier for everyone***

**Describe the issue **
A clear and concise description of what the issue is.

**XML source**
- Are you generating the XML file yourself or using an online source (please state where)? 
- Which XML file are you using (include links)?

**Affected region / channel**
- Please state what region you are in
- Please list the channel numbers that are affected/missing

**Screenshots**
- If applicable, add screenshots to help explain your problem.

**XML viewing application**
 - ie Plex/TVHeadend/Emby etc

**Additional information**
- Add any other info about the problem here.

**Comment by vw-kombi** [comment]
The 9RUSH channel is not in the gold coast xml.  Im emby, this does not show as an available guide channel to connect to the channel.  If I use the brisbane xml file instead (which works fine), then it is there.

XML source - Gold Coast – http://xmltv.net/xml_files/Goldcoast.xml

Are you generating the XML file yourself or using an online source (please state where)? - No - just keying in the url as per below.

Which XML file are you using (include links)? - http://xmltv.net/xml_files/Goldcoast.xml

Affected region / channel - 9RUSH

Please state what region you are in - Gold Coast

Please list the channel numbers that are affected/missing
9RUSH

I am using emby.  Click LiveTV, click channels, select 9RUSH, edit, use drop down on guide source, select http://xmltv.net/xml_files/Goldcoast.xml,  use drop down on Guide Channel Data, and there is no 9RUSH


Please note the Brosbane guide xml file DOES include this....

**Comment by vw-kombi** [comment]
The 9RUSH channel is not in the gold coast xml.  Im emby, this does not show as an available guide channel to connect to the channel.  If I use the brisbane xml file instead (which works fine), then it is there.

XML source - Gold Coast – http://xmltv.net/xml_files/Goldcoast.xml

Are you generating the XML file yourself or using an online source (please state where)? - No - just keying in the url as per below.

Which XML file are you using (include links)? - http://xmltv.net/xml_files/Goldcoast.xml

Affected region / channel - 9RUSH

Please state what region you are in - Gold Coast

Please list the channel numbers that are affected/missing
9RUSH

I am using emby.  Click LiveTV, click channels, select 9RUSH, edit, use drop down on guide source, select http://xmltv.net/xml_files/Goldcoast.xml,  use drop down on Guide Channel Data, and there is no 9RUSH


Please note the Brosbane guide xml file DOES include this....

**Comment by vw-kombi** [comment]
accidentally closed........  It is an issue.

**Comment by markcs** [comment]
This should be updated in the latest xml files.  Please check and revert back.
